apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gr8v84hbz-go 
  janus-idp.io/tekton: gr8v84hbz-go
  backstage.io/kubernetes-id: gr8v84hbz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gr8v84hbz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  