apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gr8v84hbz-go
  janus-idp.io/tekton: gr8v84hbz-go
  backstage.io/kubernetes-id: gr8v84hbz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gr8v84hbz-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
