apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gr8v84hbz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gr8v84hbz-go 
  name: gr8v84hbz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gr8v84hbz-go 
